# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            黑程式
tagline:          'A Jekyll theme'
description:      '不認真讀書的工程師'
url:              https://willsbor.github.io/

author:
  name:           'willsbor Kang'
  url:            https://www.facebook.com/willsbor.kang

paginate:         5
gems:             [jekyll-paginate]

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/willsbor
