# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://willsbor.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
gems:             [jekyll-paginate]

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde